-- CREATE DATABASE BANKING_SYSTEMDB; -- Created Database
USE BANKING_SYSTEMDB;  -- Accessed the database

SHOW DATABASES; -- View the Database
SHOW TABLES; -- View the tables in Database

-- Creating the Tables 

CREATE TABLE CUSTOMERS(  
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;  -- Describing the table Customers
DESCRIBE CUSTOMERS; -- Viewing the types and columns of table Customers

SELECT * 
FROM CUSTOMERS; -- viewing all rows and columns of table customers

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE; -- modifying on the table using ALTER

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTIONS(
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONE VARCHAR(20));

CREATE TABLE ACCOUNTBRANCHES(
ASSIGNEDDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL(5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES;

-- Final Modifications on Table

ALTER TABLE CUSTOMERS
DROP COLUMN ACCOUNTCREATIONDATE;

SELECT *
FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;

ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY (CUSTOMERID);

DESCRIBE CUSTOMERS;

DROP TABLE ACCOUNTBRANCHES;

SELECT *
FROM ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

DESCRIBE ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT,
ADD CONSTRAINT
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNTS(ACCOUNTID);

DESCRIBE ACCOUNTS;
DESCRIBE TRANSACTIONS;

ALTER TABLE TRANSACTIONS 
ADD PRIMARY KEY (TRANSACTIONID);

DESCRIBE TRANSACTIONS;

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BRANCHID);

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD CONSTRAINT
FOREIGN KEY (BRANCHID)
REFERENCES BRANCHES(BRANCHID);

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID INT,
ADD CONSTRAINT
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

ALTER TABLE CUSTOMERS
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAIL VARCHAR(100) UNIQUE;

DESCRIBE CUSTOMERS;

-- Adding Records inside the tables

INSERT INTO CUSTOMERS VALUE
(101,'Rahul','Sharma','rahul.sharma@gmail.com','9767983712','1995-04-12');

SELECT * 
FROM CUSTOMERS;

INSERT INTO CUSTOMERS VALUE
(102,'Veena','Kutty','veena.kutty@gmail.com','1234567890','1997-09-10'),
(103,'Dominic','Dom','dominic.dom@gmail.com',NULL,'1996-06-03'),
(104,'Alex',NULL,'alex@gmail.com','3232323232','2000-12-12'),
(105,'Alice','George',NULL,'9090909090','2003-08-10');

-- Example to show that Primary Key does not take null values

-- INSERT INTO CUSTOMERS VALUE
-- (NULL,'Rahul','Sharma','rahul.sharma@gmail.com','9767983712','1995-04-12');

INSERT INTO BRANCHES (BRANCHID,BRANCHNAME,BRANCHADDRESS,BRANCHPHONE)
VALUES (1,'Mumbai Main Branch','Andheri East, Mumbai','0220100201'),
(2,'Pune Central Branch','Shivaji Nagar, Pune','0220100202'),
(3,'Bangalore Branch','MG Road, Bangalore','0880100801'),
(4,'Delhi Branch','Connaught Palace,Delhi',NULL),
(5,'Hyderbad Branch',NULL,'0440100401');

SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO ACCOUNTS VALUES
(1001,'Savings',25000,101,1),
(1002,'Current',85000.50,102,2),
(1003,'Savings',12500.75,103,1),
(1004,'Salary',45000,104,3),
(1005,'Savings',7800.25,105,2),
(1006,'Savings',42000,101,2),
(1007,'Current',NULL,103,3),
(1008,'Savings',27500,105,4);

INSERT INTO TRANSACTIONS VALUES
(5001,'2026-01-05',10000,'Deposit',1001),
(5002,'2026-01-10',2500,'Withdrawal',1001),
(5003,'2026-01-15',5000,'Transfer',1002),
(5004,'2026-01-20',15000,'Deposit',1003),
(5005,'2026-01-25',3000,'Withdrawal',1004),
(5006,'2026-02-02',7500,'Deposit',1005),
(5007,'2026-02-05',1200,'Payment',1006),
(5008,'2026-02-10',NULL,'Deposit',1007),
(5009,'2026-02-15',8500,'Withdrawal',1008),
(5010,NULL,100,'Payment',1003),
(5011,'2026-02-20',20000,'Transfer',1006),
(5012,'2026-03-01',5000,'Deposit',1002),
(5013,'2026-03-05',10000,'Withdrawal',1007),
(5014,'2026-03-15',1500,'Deposit',1008),
(5015,'2026-03-20',25000,'Transfer',1005);

INSERT INTO LOANS VALUES
(9001,500000,8.50,'2025-01-15','2030-01-15',101),
(9002,250000,9.25,'2025-03-10','2028-03-10',103),
(9003,NULL,9.00,'2026-03-01',NULL,105),
(9004,750000,7.90,'2024-06-20','2031-06-20',102),
(9005,1000000,7.25,'2024-11-15','2034-11-15',104),
(9006,300000,10.50,'2025-07-01','2029-07-01',101);

-- Checking the Data

SELECT * 
FROM CUSTOMERS;

SELECT * 
FROM BRANCHES;

SELECT * 
FROM ACCOUNTS;

SELECT * 
FROM TRANSACTIONS;

SELECT * 
FROM LOANS;

-- Updating and Deleting Records

UPDATE CUSTOMERS
SET PHONE = "4345667890"
WHERE CUSTOMERID = 103; -- UPDATED A PHONE NUMBER

DELETE FROM TRANSACTIONS
WHERE TRANSACTIONID = 5008; -- DELETED A USELESS RECORD

UPDATE ACCOUNTS
SET BALANCE = 35750
WHERE ACCOUNTID = 1007; -- UPDATED THE BALANCE 

UPDATE TRANSACTIONS
SET ACCOUNTID = 1003
WHERE TRANSACTIONID IN (5006,5007); -- UPDATED MULTIPLE RECORDS

-- EXTRACING THE DATA

SELECT FIRSTNAME,EMAIL,CUSTOMERID
FROM CUSTOMERS; 

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID = 105; -- CALLING SPECIFIC DATA

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID = 102 OR CUSTOMERID = 104; -- CALLING MULTIPLE ID'S

SELECT *  -- CALLING DATA IN RANGE 
FROM CUSTOMERS
WHERE BIRTHDATE >= '1995-01-01' AND BIRTHDATE <= '2000-12-31';

-- Customer Analysis

-- How many customers are there?

SELECT COUNT(*) AS Total_Customers -- Column Alises 
FROM CUSTOMERS;

-- Which customers have missing information?

SELECT CUSTOMERID, FIRSTNAME AS NAME
FROM CUSTOMERS
WHERE LASTNAME IS NULL OR EMAIL IS NULL;

-- Who are the youngest/oldest customers?

SELECT
MAX(BIRTHDATE) AS YOUNGEST_CUSTOMER,
MIN(BIRTHDATE) AS OLDEST_CUSTOMER
FROM CUSTOMERS;

-- How many customers were born before/after a particular year?

-- Before 2000

SELECT * 
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) <= 2000;

-- After 2000

SELECT * 
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) > 2000;

-- Which customers have multiple accounts?

SELECT CUSTOMERID, COUNT(*) AS Total_Accounts
FROM ACCOUNTS
GROUP BY CUSTOMERID
HAVING Total_Accounts > 1;

-- ACCOUNT ANALYSIS

-- How many Savings, Current and Salary accounts exist?

SELECT ACCOUNTTYPE,COUNT(*) AS Total_Accounts
FROM ACCOUNTS
GROUP BY ACCOUNTTYPE;

-- What is the total balance?

SELECT SUM(BALANCE) Total_Balance
FROM ACCOUNTS;

-- What is the average account balance?

SELECT AVG(BALANCE) Average_Balance
FROM ACCOUNTS;

-- Which customers have the highest balances?

SELECT CUSTOMERID, BALANCE Highest_Balance
FROM ACCOUNTS
ORDER BY BALANCE DESC LIMIT 1;

-- Which accounts have NULL balances?

SELECT *
FROM ACCOUNTS
WHERE BALANCE=NULL;

-- Which branch manages the most accounts?

SELECT BRANCHID,COUNT(*) Total_Accounts
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Accounts DESC LIMIT 1;

-- Transaction Analysis

-- What is the total transaction amount?

SELECT SUM(AMOUNT) Total_Transaction_Amount
FROM TRANSACTIONS;

-- How many deposits/withdrawals/transfers are there?

SELECT TRANSACTIONTYPE, COUNT(*) Total_Transactions
FROM TRANSACTIONS
WHERE TRANSACTIONTYPE IN ('Deposit','Withdrawal','Transfer')
GROUP BY TRANSACTIONTYPE;

-- Which transaction type has the highest volume?

SELECT TRANSACTIONTYPE,SUM(AMOUNT) Total_Amount
FROM TRANSACTIONS
GROUP BY TRANSACTIONTYPE
ORDER BY Total_Amount DESC LIMIT 1;

-- Which account has the highest transaction activity?

SELECT ACCOUNTID, COUNT(*) Total_Transactions
FROM TRANSACTIONS
GROUP BY ACCOUNTID
ORDER BY Total_Transactions DESC LIMIT 1;

-- What is the average transaction amount?

SELECT AVG(AMOUNT) Average_Transaction_Amount
FROM TRANSACTIONS;

-- Which transactions have missing dates/amounts?

SELECT *
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NULL OR AMOUNT IS NULL;

-- Loan Analysis

-- What is the total loan amount?

SELECT SUM(LOANAMOUNT) Total_Loans
FROM LOANS;

-- Which customer has the largest loan?

SELECT CUSTOMERID, SUM(LOANAMOUNT) Total_Loans
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY Total_Loans DESC LIMIT 1;

-- Which loan has the highest interest rate?

SELECT MAX(INTERESTRATE) Highest_Interest_Rate 
FROM LOANS;

-- Which loans are still active?

SELECT * 
FROM LOANS
WHERE YEAR(ENDDATE) > 2026;

-- Which customers have multiple loans?

SELECT CUSTOMERID, COUNT(*) Total_Loans
FROM LOANS
GROUP BY CUSTOMERID
HAVING Total_Loans > 1;

-- What is the average loan amount?

SELECT AVG(LOANAMOUNT) Average_Loan_Amount
FROM LOANS;

-- Branch Analysis

-- Which branch has the most customers/accounts?

-- Branch with most Accounts

SELECT BRANCHID,COUNT(*) Total_Accounts 
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Accounts DESC LIMIT 1;

-- Branch with most Customers

SELECT BRANCHID,COUNT(CUSTOMERID) Total_Customers
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Customers DESC LIMIT 1;

-- Which branch has the highest total account balance?

SELECT BRANCHID, SUM(BALANCE) Total_Account_Balance
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY Total_Account_Balance DESC LIMIT 1;

-- Which branch handles the most transactions?

-- Account with Max Transactions

SELECT ACCOUNTID, COUNT(*) Total_Transactions 
FROM TRANSACTIONS
GROUP BY ACCOUNTID 
ORDER BY Total_transactions DESC LIMIT 1;

-- Branch with Max Transactions

SELECT BRANCHID
FROM ACCOUNTS
WHERE ACCOUNTID = 1003;

-- Which branch has the highest loan exposure?

-- Customer with Max Loan Amount

SELECT CUSTOMERID, SUM(LOANAMOUNT) Total_Loan_Amount
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY Total_Loan_Amount DESC LIMIT 1;

-- Branch with Max Loan Amount

SELECT BRANCHID 
FROM ACCOUNTS
WHERE CUSTOMERID = 104;


SET FOREIGN_KEY_CHECKS = 0; -- For allowing updation / deletion of data

-- Functions

-- String Functions

-- CONCAT() COMBINES MULTIPLE STRINGS

SELECT CUSTOMERID, concat(FIRSTNAME," ",LASTNAME) AS FULL_NAME
FROM CUSTOMERS;

-- UPPER()

-- IT CONVERTS THE CASES INTO UPPER CASES

SELECT CUSTOMERID, UPPER(concat(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM CUSTOMERS;

-- LOWER()

-- IT CONVERTS THE CASES INTO LOWER CASES

SELECT CUSTOMERID, LOWER(concat(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM CUSTOMERS;

-- LENGTH()
-- FINDS THE NUMBER OF LENGTH

SELECT FIRSTNAME, LENGTH(FIRSTNAME) AS NAMELENGTH
FROM CUSTOMERS
HAVING NAMELENGTH <= 5
ORDER BY NAMELENGTH DESC LIMIT 1 OFFSET 1; -- OFFSET IS USED TO SKIP THE VALUES

-- CHAR_LENGTH()

-- CALCULATES THE NUMBER OF STRINGS

SELECT FIRSTNAME, char_length(FIRSTNAME) AS CHARACTER_LENGTH
FROM CUSTOMERS;

-- LEFT()
-- EXTRACTS THE DATA FROM LEFT SIDE

SELECT FIRSTNAME, LEFT(FIRSTNAME,3) AS FIRST_3_CHAR
FROM CUSTOMERS;

-- RIGHT()

-- EXTRACTS DATA FROM THE RIGHT SIDE

SELECT PHONE, RIGHT(PHONE,4) AS LAST4DIGITS
FROM CUSTOMERS;

-- DISPLAY MASKED ACCOUNT

SELECT CUSTOMERID, CONCAT("XXXXXX",RIGHT(PHONE,4)) AS MASKED_PHONE
FROM CUSTOMERS;

-- SUBSTRING()

-- IT EXTRACTS THE PORTION OF A STRING

SELECT EMAIL, SUBSTRING(EMAIL,1,5) AS EMAIL_PART
FROM CUSTOMERS; 	

-- SUBSTRING_INDEX()

SELECT EMAIL, substring_index(EMAIL,"@",1) AS EMAIL_PART
FROM CUSTOMERS;

-- TRIM()
-- REMOVES USELESS SPACES

SELECT TRIM("Veena Kutty     ") AS NAME;

-- REPLACE()
-- REPLACES THE VALUES

SELECT EMAIL, REPLACE(EMAIL,'gmail.com','email.com') AS EMAILS
FROM CUSTOMERS;

-- LOCATE()
-- FINDS THE POSITION OF THE CHARACTER/STRING

SELECT EMAIL,LOCATE("@",EMAIL) AS POSITION
FROM CUSTOMERS;

-- MATH FUNCTIONS

-- ROUND()
-- ROUNDS OFF THE DECIMAL VALUES

SELECT ACCOUNTID,BALANCE,ROUND(BALANCE,0) AS ROUNDED_BALANCE
FROM ACCOUNTS;

-- CEIL()/CEILING()
-- IT ROUNDS UP THE VALUE

SELECT BALANCE,CEIL(BALANCE) AS ROUNDUP_BALANCE
FROM ACCOUNTS;

-- FLOOR()
-- IT ROUNDS DOWN THE VALUE

SELECT BALANCE,FLOOR(BALANCE) AS ROUNDDOWN_BALANCE
FROM ACCOUNTS;

-- ABS()
-- RETURNS THE ABSOLUTE VALUE

SELECT ABS(-8754) AS ABSOLUTE_VALUE;

-- MOD()
-- RETURNS REMAINING VALUE

SELECT ACCOUNTID,MOD(ACCOUNTID,2) AS REMINDER
FROM ACCOUNTS;

-- CASE THEN END IS JUST LIKE IF - ELSE STATMENT

SELECT ACCOUNTID,MOD(ACCOUNTID,2) AS REMINDER,CASE
WHEN MOD(ACCOUNTID,2)=0 THEN "Even"
ELSE "Odd"
END AS ID_TYPE
FROM ACCOUNTS;

-- POWER()
--  WORKS LIKE INDICES

SELECT POWER(2,4) AS RESULT;

-- SQRT()
-- RETURNS THE SQUARE ROOT OF THE VALUE

SELECT BALANCE,SQRT(BALANCE) AS SQRT_BALANCE
FROM ACCOUNTS;

-- GREATEST()
-- COMPARES VALUES 

SELECT ACCOUNTID, BALANCE,GREATEST(BALANCE,25000) AS MINIMUM_BALANCE
FROM ACCOUNTS;

-- LEAST()
-- COMPARES VALUES

SELECT ACCOUNTID,BALANCE,LEAST(BALANCE,50000) AS MAX_LIMIT
FROM ACCOUNTS;

-- CALCULATE ANNUAL INTEREST

SELECT LOANID,LOANAMOUNT,INTERESTRATE, ROUND(LOANAMOUNT * INTERESTRATE / 100,2) AS ANNUAL_INTEREST
FROM LOANS;

-- LOAN AMOUNT + INTEREST

SELECT LOANID,LOANAMOUNT,INTERESTRATE, 
ROUND(LOANAMOUNT + (LOANAMOUNT * INTERESTRATE / 100),2) AS PRINCIPAL_PLUS_ONEYEAR_INTEREST
FROM LOANS;

-- BALANCE CATEGORY

SELECT ACCOUNTID, BALANCE,
CASE
WHEN BALANCE IS NULL THEN "Unkown"
WHEN BALANCE < 10000 THEN "Low"
WHEN BALANCE < 50000 THEN "Medium"
ELSE "High"
END AS BALANCE_CATEGORY
FROM ACCOUNTS;

-- DATE & TIME FUNCTIONS

SELECT CURDATE() AS TODAY; -- TODAY'S DATE
SELECT SYSDATE() AS TODAY; -- TODAY'S DATE WITH TIME

-- YEAR()

SELECT CUSTOMERID,BIRTHDATE,YEAR(BIRTHDATE) AS BIRTH_YEAR
FROM CUSTOMERS;

-- MONTH()

SELECT TRANSACTIONID,TRANSACTIONDATE,MONTH(TRANSACTIONDATE) AS TRANSACTION_MONTH
FROM TRANSACTIONS;

-- MONTHNAME()

SELECT TRANSACTIONID,TRANSACTIONDATE,MONTHNAME(TRANSACTIONDATE) AS TRANSACTION_MONTH
FROM TRANSACTIONS;

-- DAY()

SELECT TRANSACTIONID,TRANSACTIONDATE,DAY(TRANSACTIONDATE) AS DAY_NUMBER
FROM TRANSACTIONS;

-- DAYNAME()

SELECT TRANSACTIONID,TRANSACTIONDATE,DAYNAME(TRANSACTIONDATE) AS DAY_NAME
FROM TRANSACTIONS;

-- QUARTER()

SELECT TRANSACTIONID,TRANSACTIONDATE,QUARTER(TRANSACTIONDATE) AS QUARTER_NUMBER
FROM TRANSACTIONS;

SELECT QUARTER(TRANSACTIONDATE) AS QUARTERS,COUNT(*) AS TRANSACTION_COUNT,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY QUARTER(TRANSACTIONDATE);

-- DATEDIFF()

SELECT LOANID,STARTDATE,ENDDATE,DATEDIFF(ENDDATE,STARTDATE) AS LOAN_DAYS
FROM LOANS;

-- CALCULATE LOAN DURATION IN TERMS OF YEAR

SELECT LOANID,STARTDATE,ENDDATE,ROUND(DATEDIFF(ENDDATE,STARTDATE)/365,2) AS LOAN_YEARS
FROM LOANS
WHERE ENDDATE IS NOT NULL;

-- TIMESTAMDIFF()

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE
FROM CUSTOMERS;

-- AGE GROUP

SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE,
CASE
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) < 25 THEN "Young Adult"
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) BETWEEN 25 AND 40 THEN "Adult"
ELSE "Senior"
END AS AGE_GROUP
FROM CUSTOMERS;

-- DATE_FORMAT()

SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE,'%d-%m-%Y') AS FORMATED_DATE
FROM TRANSACTIONS;

SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE,'%M-%Y') AS MONTH_YEAR
FROM TRANSACTIONS;

-- MONTHLY TRANSACTIONS

SELECT 
DATE_FORMAT(TRANSACTIONDATE,'%Y-%m') AS MONTH,
COUNT(*) AS TRANSACTION_COUNTS,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY DATE_FORMAT(TRANSACTIONDATE,'%Y-%m')
ORDER BY MONTH;

-- LAST 30 DAYS TRANSACTIONS

SELECT *
FROM TRANSACTIONS
WHERE TRANSACTIONDATE >= DATE_SUB('2026-02-25',INTERVAL 30 DAY);

-- ADDING DAYS TO THE DATE

SELECT TRANSACTIONID,TRANSACTIONDATE,DATE_ADD(TRANSACTIONDATE,INTERVAL 30 DAY) AS AFTER_30_DAYS
FROM TRANSACTIONS;

-- LOAN STATUS USING DAYS

SELECT LOANID, STARTDATE,ENDDATE,
CASE
WHEN ENDDATE IS NULL THEN "No End Date"
WHEN ENDDATE <CURDATE() THEN "Completed"
ELSE "Active"
END AS LOAN_STATUS
FROM LOANS;